### PR TITLE
Tickets/sitcom 1101

### PR DESCRIPTION
**Pull request by joaquinhernandezg**
Pull Request Associated to [SITCOM-1101](https://jira.lsstcorp.org/browse/SITCOM-1101) 

Changes:
 - Migrate to new technote format according to https://documenteer.lsst.io/technotes/migrate.html
 - Update section titles to not include ticket names 
 - Add the associated ticket and notebook below each section
 - Add a Section of requirements to be validated(This need to be checked, as slew position requierements are not correct in the analysis)
 - Add a links to the Related SITCOM tickets
 - Add a telemetry section
 - Improve the redaction in Section "Compensating Mirror Motion with the Hexapods" for clarity. Make the goal more explicit.
 - Put all the TN links at the top the .srt file for manteinability.

### CODE REVIEW

**Comment by b1quint** [comment]
This looks very good. Thank you for making the changes explicit into the PR! I have a few requests to make thought:

1. Can you squash commits to have a cleaner timeline? For example, there is one commit simply saying `typo`. That one can easily be squashed with the previous ones. 
2. Can you rename the "Update LVV-T235 notebook" session to something clearer? The notebook says, "Position Repeatability After Parking." Maybe add that instead? 

Question for @boutigny: would it be clearer/more intuitive to move the "Telemetry" session before all the analysis? Let's say, between "Related SITCOM tickets" and "Slewing analysis - Positioning"?

**Comment by boutigny** [comment]
@b1quint yes, it would certainly be clearer / more logic to put the telemetry section before.

**Comment by joaquinhernandezg** [comment]
@b1quint following your suggestions
- Squash is done
- Telemetry section was moved where sugested
- "Update LVV-T235 notebook" section is renamed to   "Position Repeatability After Parking".

**Review by b1quint — APPROVED** [review]
Looks good! It is ready to merge. Thank you very much!

**Pull request merged**
