### PR TITLE
Tickets/sitcom 1189

### PR DESCRIPTION
**Pull request by boutigny**
Include results from SITCOM-1159 analysis

### CODE REVIEW

**Comment by joaquinhernandezg** [comment]
Everything looks good! I just have one comment.

According to Figure 2, slews have amplitude of at least 50 deg, as seen in Elevation Difference axis. Requirements specified in TS-88-REQ-0052, which are plotted  in the figures, are for slews of amplitudes less than 3.5 deg. For larger amplitudes we have LTS-88-REQ-0053 which is a bit more flexible the specifications.
According to the data used, we are actually analyzing LTS-88-REQ-0053 and not LTS-88-REQ-0052. 
Given that you made modificatons to the plots in sections "Slewing analysis - Positioning", "Slewing in Azimuth Analysis - Positioning", and "Position and Rotation Repeatibility for a Specific Target Elevation.",  **I propose changing the limits of the requirements in the plots and verify if the difference still out of tolerance intervals**, and repeating the analysis for LTS-88-REQ-0052 with other dataset (with just small-amplitude slews) in a new ticket. 
Maybe changing the limits can be another ticket by itself. What are @b1quint thoughts of this?

Appart from that, I'd say that the specifications for [SITCOM-1189](https://jira.lsstcorp.org/browse/SITCOM-1189) are met.

**Comment by b1quint** [comment]
I believe that a discussion during our meeting could help clarify things (unfortunately, I will have to miss it). We might want to split the analysis if we have different requirements. However, I would do this work by separating the requirements and analysis in a new PR.

**Comment by boutigny** [comment]
The original analysis detailed in this technical note correspond to SITCOM-797 that doesn't distinguish between short and long slews. In fact I just discover that there is such a distinction (I didn't know about LTS-88 until you mentioned it). 
It should definitely be taken into account but I suggest to proceed incrementally and to merge this version of the TN and then to open a separate ticket.
We already know that the piston requirement for long slew in elevation is not met (fig. 1) 
Please tell me if you agree and if I go ahead to merge this branch

**Comment by joaquinhernandezg** [comment]
I completely agree with this, proceed with the merge.

**Pull request merged**
